### ISSUE TITLE
crushed when I using keyboard to input something

### ISSUE THREAD

**Issue by fenyunzaiqu** [backslash-f/ShockEmu#10]
./run.sh: line 3: 11308 Segmentation fault: 11  DYLD_FORCE_FLAT_NAMESPACE=1 DYLD_INSERT_LIBRARIES=iohid_wrap.dylib /Applications/RemotePlay.app/Contents/MacOS/RemotePlay > /dev/null 2>&1

macOS 12.0.1 apple MacBook m1 pro13' python3.9.
System Integrity Protection status: disabled.

crushed when I using keyboard to input something

**Comment by backslash-f** [comment]
Yeah, that sucks. :-(
Duplicated of https://github.com/backslash-f/ShockEmu/issues/9

**Comment by fenyunzaiqu** [comment]
what a pity😭

**Comment by fenyunzaiqu** [comment]
@backslash-f  hi, I have a review of code. I think may macOS 11 or later doesn't support iokit. https://developer.apple.com/documentation/iokit.  
It is said
「Devices supported on macOS 11 and later require DriverKit. Use IOKit in your apps and services to discover and use devices.」

Do you have any idea of replace iokit to DriverKit? Or my idea is simply wrong. (No experience on iOS/object-c developing)

**Comment by backslash-f** [comment]
@fenyunzaiqu yes, nice catch. I've opened a bug for it already. https://github.com/backslash-f/ShockEmu/issues/1 (on macOS 11+, it has to use HIDDriverKit instead). But I don't know how to do that yet... The issue is opened, let's hope someone else more knowledgeable would jump in.

**Comment by fenyunzaiqu** [comment]
@backslash-f I read a little DriverKit document. I want to run the sample code of DriverKit. But it said 「you should join in Apple Developer Program to get provisioning profile」. I don't know why Apple want me to pay them 99$ a year when I want to study a framework and api. Now I can't do nothing either😭. Maybe I should try to install macOS 10 to see if it works.

**Comment by backslash-f** [comment]
I think you only need to pay if you want to distribute apps:

`
You can learn how to develop apps for Apple platforms for free without enrolling. With just an Apple ID, you can access Xcode, software downloads, documentation, sample code, forums, and Feedback Assistant, as well as test your apps on devices. If you don’t already have an Apple ID, you can create one now. To distribute apps, join the Apple Developer Program.
`
https://developer.apple.com/support/compare-memberships/

I cannot confirm though, because I have a paid account.
